version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - cyclop
    - err113
    - exhaustruct
    - gochecknoglobals
    - lll
    - noinlineerr
    - nonamedreturns
    - varnamelen
    - testpackage
    - funlen
    - wsl
  settings:
    depguard:
      rules:
        main:
          # Packages that are not allowed where the value is a suggestion.
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib 'errors' package
            - pkg: github.com/hashicorp/go-multierror
              desc: Should be replaced by standard lib 'errors' package
            - pkg: go.uber.org/multierr
              desc: Should be replaced by standard lib 'errors' package
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - fmt.Printf
        - fmt.Fprintf
    iface:
      enable:
        - identical # Identifies interfaces in the same package that have identical method sets.
        - unused # Identifies interfaces that are not used anywhere in the same package where the interface is defined.
        - opaque # Identifies functions that return interfaces, but the actual returned value is always a single concrete implementation.
    govet:
      enable-all: true
    prealloc:
      for-loops: true
    revive:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: atomic
        - name: banned-characters
          arguments: [Ω,Σ,σ,"7"]
        - name: bare-return
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: call-to-gc
        - name: cognitive-complexity
          disabled: true
        - name: comment-spacings
        - name: comments-density
          disabled: true
        - name: confusing-naming
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: context-keys-type
        - name: cyclomatic
          disabled: true
        - name: datarace
        - name: deep-exit
        - name: defer
          arguments:
            - ["call-chain", "loop", "method-call", "recover", "immediate-recover", "return"]
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: enforce-map-style
          arguments: ["make"]
          exclude: ["TEST"]
        - name: enforce-repeated-arg-type-style
          arguments:
            - { funcArgStyle = "any", funcRetValStyle = "short" }
        - name: enforce-slice-style
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"
          disabled: true
        - name: file-header
          disabled: true
        - name: flag-parameter
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: get-return
        - name: identical-branches
        - name: if-return
        - name: import-alias-naming
          arguments:
            - "^[a-z][a-z0-9]{0,}$"
        - name: import-shadowing
        - name: imports-blocklist
          disabled: true
        - name: increment-decrement
        - name: indent-error-flow
        - name: line-length-limit
          disabled: true
        - name: max-control-nesting
        - name: max-public-structs
          arguments: [5]
          exclude: ["TEST"]
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: nested-structs
        - name: optimize-operands-order
        - name: package-comments
          disabled: true
        - name: range
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-import-alias
        - name: string-format
          arguments:
            - - 'fmt.Errorf[0]'
              - '/^([^A-Z]|$)/'
              - 'Error string must not start with a capital letter.'
            - - 'fmt.Errorf[0]'
              - '/(^|[^\.!?])$/'
              - 'Error string must not end in punctuation.'
            - - 'errors.New[0]'
              - '/^([^A-Z]|$)/'
              - 'Error string must not start with a capital letter.'
            - - 'errors.New[0]'
              - '/(^|[^\.!?])$/'
              - 'Error string must not end in punctuation.'
            - - 'panic'
              - '/^[^\n]*$/'
              - 'Must not contain line breaks.'
        - name: string-of-int
        - name: struct-tag
          arguments:
            - "json,inline"
        - name: superfluous-else
        - name: time-equal
        - name: time-naming
        - name: unchecked-type-assertion
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unhandled-error
          arguments:
            - "^(fmt.Printf|fmt.Fprintf)"
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: use-any
        - name: useless-break
        - name: var-declaration
        - name: var-naming
        - name: waitgroup-by-value
    staticcheck:
      # https://staticcheck.dev/docs/checks
      checks:
        - all
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    warn-unused: true
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows declaration'
      - linters:
          - govet
        path: (.*_test\.go|test\/)
        text: 'fieldalignment: '

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/zerospiel/pidof) # Custom section: groups all imports with the specified Prefix.
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    gofumpt:
      extra-rules: true
  exclusions:
    generated: strict

output:
  sort-order:
    - linter
    - severity
    - file # filepath, line, and column.

severity:
  default: "@linter"
issues:
  max-same-issues: 0
  max-issues-per-linter: 0