version: 2

project_name: pidof

before:
  hooks:
    - go mod tidy

builds:
  - id: pidof
    main: ./cmd
    binary: pidof
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X github.com/zerospiel/pidof/internal/pidof.version={{ .Version }}
        -X github.com/zerospiel/pidof/internal/pidof.buildTime={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: tarballs
    formats:
      - tar.gz
    ids:
      - pidof
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" -}}Darwin
      {{- else if eq .Os "linux" -}}Linux
      {{- else -}}{{ .Os }}{{- end -}}_
      {{- if eq .Arch "amd64" -}}x86_64
      {{- else if eq .Arch "386" -}}i386
      {{- else if eq .Arch "arm64" -}}arm64{{- else -}}{{ .Arch }}{{- end -}}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "Features"
      regexp: '^.*?(feat)(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Others"
      order: 9999

snapshot:
  version_template: "{{ .Version }}-{{ .ShortCommit }}{{ if .IsGitDirty }}-dirty{{ end }}"

release:
  github:
    owner: zerospiel
    name: pidof
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## pidof {{ .Tag }}

  footer: |
    ---
    ## Homebrew

    Install:

    `brew install zerospiel/tools/pidof`
    ---
    **Full Changelog**: https://github.com/zerospiel/pidof/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: pidof
    ids:
      - tarballs
    directory: Formula
    repository:
      owner: zerospiel
      name: homebrew-tools
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/zerospiel/pidof
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    license: "MIT"
    skip_upload: auto
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: Display the PID number for a given process name(s). Drop-in replacement for the deprecated NightProductions pidof.
    test: |
      assert_match "pidof", shell_output("#{bin}/pidof --version")
