name: Validate

on:
  pull_request:
    branches:
      - master
    paths:
      - ".goreleaser.yaml"
      - "cmd/**"
      - "internal/**"
      - "go.mod"
      - "go.sum"

jobs:
  goreleaser-validate:
    name: GoReleaser Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Validate GoReleaser config
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: check

      - name: Test GoReleaser build
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot --clean
